"""Shared State model definitions for Multi-Agent Research Assistant.

This module provides the central explicit shared state that flows through all agents:
Coordinator -> Research Agent -> Analyzer -> Critic -> Writer -> Coordinator.
"""

from __future__ import annotations
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
import uuid


class Finding(BaseModel):
    """An individual research finding discovered by the Research Agent."""
    id: str = Field(default_factory=lambda: f"fnd_{uuid.uuid4().hex[:6]}")
    title: str
    fact: str
    evidence: str
    source_id: str
    confidence: float = 1.0  # 0.0 to 1.0
    domain: Optional[str] = "General"


class SourceReference(BaseModel):
    """Source material or reference cataloged by the Research Agent."""
    id: str = Field(default_factory=lambda: f"src_{uuid.uuid4().hex[:6]}")
    title: str
    url_or_doi: str
    publication_year: Optional[int] = 2024
    author_or_org: str
    relevance_summary: str


class AnalysisTheme(BaseModel):
    """Synthesized theme extracted by the Analyzer agent."""
    theme_id: str = Field(default_factory=lambda: f"thm_{uuid.uuid4().hex[:6]}")
    name: str
    summary: str
    supporting_finding_ids: List[str] = Field(default_factory=list)
    impact_level: str = "High"  # High, Medium, Low


class CriticEvaluation(BaseModel):
    """Quality review and critique produced by the Critic agent."""
    quality_score: float = Field(default=8.5, description="Score out of 10.0")
    passes_validation: bool = True
    needs_refinement: bool = False
    target_refinement_stage: Optional[str] = None  # e.g., "research" or "analyzer"
    identified_issues: List[str] = Field(default_factory=list)
    missing_information: List[str] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)
    bias_assessment: str = "Neutral and fact-grounded"
    overall_assessment: str = "Meets research quality thresholds."


class FinalReportSection(BaseModel):
    """Structured report section generated by the Writer."""
    heading: str
    content: str


class AgentExecutionRecord(BaseModel):
    """Execution metadata for tracking agent observability."""
    agent: str
    start_time: str
    end_time: str
    duration_seconds: float
    status: str  # "running", "completed", "failed", "retrying"
    input_summary: str
    output_summary: str
    error_information: Optional[str] = None
    step_index: int = 0
    iteration: int = 1


class ResearchState(BaseModel):
    """Explicit Shared State object passed and updated throughout the multi-agent workflow.
    
    Every agent reads only the state it requires and writes its designated outputs.
    The Coordinator monitors, orchestrates, and records execution history.
    """
    workflow_id: str = Field(default_factory=lambda: f"wf_{uuid.uuid4().hex[:8]}")
    query: str
    preferences: Dict[str, Any] = Field(default_factory=dict)
    
    # Workflow orchestration state
    workflow_status: str = "initialized"  # initialized, planning, running, completed, failed
    workflow_plan: List[str] = Field(default_factory=lambda: ["research", "analyze", "criticize", "write"])
    current_step: Optional[str] = None
    refinement_iterations: int = 0
    max_refinements: int = 1
    
    # Stage 1: Research Agent outputs
    research_findings: List[Finding] = Field(default_factory=list)
    sources: List[SourceReference] = Field(default_factory=list)
    research_notes: str = ""
    
    # Stage 2: Analyzer Agent outputs
    analysis: Dict[str, Any] = Field(default_factory=dict)
    
    # Stage 3: Critic Agent outputs
    critique: Dict[str, Any] = Field(default_factory=dict)
    
    # Stage 4: Writer Agent outputs
    final_report: str = ""
    report_metadata: Dict[str, Any] = Field(default_factory=dict)
    
    # Observability & Diagnostics
    agent_history: List[AgentExecutionRecord] = Field(default_factory=list)
    errors: List[Dict[str, Any]] = Field(default_factory=list)
    
    def add_history(self, record: AgentExecutionRecord) -> None:
        """Appends an execution record to the state history."""
        self.agent_history.append(record)

    def add_error(self, agent: str, error_message: str, error_type: str = "ExecutionError", retry_count: int = 0) -> None:
        """Records an error event in the state."""
        self.errors.append({
            "agent": agent,
            "error_type": error_type,
            "message": error_message,
            "retry_count": retry_count,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

    def get_finding_by_id(self, finding_id: str) -> Optional[Finding]:
        for f in self.research_findings:
            if f.id == finding_id:
                return f
        return None

    def get_source_by_id(self, source_id: str) -> Optional[SourceReference]:
        for s in self.sources:
            if s.id == source_id:
                return s
        return None

    def to_summary_dict(self) -> Dict[str, Any]:
        """Returns a high-level summary view of the workflow state."""
        return {
            "workflow_id": self.workflow_id,
            "query": self.query,
            "workflow_status": self.workflow_status,
            "current_step": self.current_step,
            "findings_count": len(self.research_findings),
            "sources_count": len(self.sources),
            "has_analysis": bool(self.analysis),
            "has_critique": bool(self.critique),
            "has_report": bool(self.final_report),
            "critique_score": self.critique.get("quality_score") if isinstance(self.critique, dict) else None,
            "refinement_iterations": self.refinement_iterations,
            "agent_history_count": len(self.agent_history),
            "error_count": len(self.errors),
        }
